import { formatTimestamp } from '../services/transcriptionService';

export async function exportToDocx(transcript, videoName) {
    try {
        const docx = await import('docx');
        const { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, Packer } = docx;

        const doc = new Document({
            sections: [{
                properties: {},
                children: [
                    new Paragraph({
                        text: 'Video Transcript',
                        heading: HeadingLevel.HEADING_1,
                        alignment: AlignmentType.CENTER,
                        spacing: { after: 400 }
                    }),

                    new Paragraph({
                        children: [
                            new TextRun({
                                text: 'Video: ',
                                bold: true
                            }),
                            new TextRun(videoName)
                        ],
                        spacing: { after: 200 }
                    }),

                    new Paragraph({
                        children: [
                            new TextRun({
                                text: 'Duration: ',
                                bold: true
                            }),
                            new TextRun(formatTimestamp(transcript.duration * 1000))
                        ],
                        spacing: { after: 400 }
                    }),

                    ...transcript.segments.flatMap(segment => [
                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: `[${formatTimestamp(segment.start)}] `,
                                    bold: true,
                                    color: '6366f1'
                                }),
                                new TextRun(segment.text)
                            ],
                            spacing: { after: 200 }
                        })
                    ]),

                    new Paragraph({
                        text: '\n\nGenerated by MWN Video Transcription',
                        alignment: AlignmentType.CENTER,
                        spacing: { before: 400 }
                    })
                ]
            }]
        });

        const blob = await Packer.toBlob(doc);

        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${videoName}_transcript.docx`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
    } catch (error) {
        console.error('Error exporting to DOCX:', error);
        throw error;
    }
}

export async function exportToPdf(transcript, videoName) {
    try {
        const { default: jsPDF } = await import('jspdf');
        await import('jspdf-autotable');

        const doc = new jsPDF();

        doc.setFontSize(20);
        doc.setFont(undefined, 'bold');
        doc.text('Video Transcript', 105, 20, { align: 'center' });

        doc.setFontSize(12);
        doc.setFont(undefined, 'normal');
        doc.text(`Video: ${videoName}`, 20, 35);
        doc.text(`Duration: ${formatTimestamp(transcript.duration * 1000)}`, 20, 42);
        doc.text(`Confidence: ${(transcript.confidence * 100).toFixed(1)}%`, 20, 49);

        const tableData = transcript.segments.map(segment => [
            formatTimestamp(segment.start),
            segment.text
        ]);

        doc.autoTable({
            startY: 60,
            head: [['Timestamp', 'Text']],
            body: tableData,
            theme: 'grid',
            headStyles: {
                fillColor: [99, 102, 241],
                fontSize: 11,
                fontStyle: 'bold'
            },
            columnStyles: {
                0: { cellWidth: 30, fontStyle: 'bold' },
                1: { cellWidth: 150 }
            },
            styles: {
                fontSize: 10,
                cellPadding: 5
            },
            margin: { left: 20, right: 20 }
        });

        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(10);
            doc.text(
                'Generated by MWN Video Transcription',
                105,
                doc.internal.pageSize.height - 10,
                { align: 'center' }
            );
        }

        doc.save(`${videoName}_transcript.pdf`);
    } catch (error) {
        console.error('Error exporting to PDF:', error);
        throw error;
    }
}
